name: Scala CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21

      - name: Install sbt (via coursier)
        uses: coursier/setup-action@v1
        with:
          apps: sbt

      - name: Compile
        run: sbt compile

      - name: Run Tests
        run: sbt test